# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170821_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='privilegio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='senha',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='val15seg',
            table=None,
        ),
    ]
