# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Constantes',
        ),
        migrations.DeleteModel(
            name='DadoGrafico',
        ),
        migrations.DeleteModel(
            name='Val15Seg',
        ),
        migrations.DeleteModel(
            name='Val5Min',
        ),
    ]
