# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chave_senha_requisitada',
            field=models.CharField(max_length=64, null=True, verbose_name='Chave requisição de senha'),
        ),
        migrations.AddField(
            model_name='user',
            name='senha_foi_requisitada',
            field=models.BooleanField(default=False, verbose_name='Senha foi requisitada?'),
        ),
        migrations.AddField(
            model_name='user',
            name='senha_requisitada_em',
            field=models.DateTimeField(null=True, verbose_name='data requisição'),
        ),
    ]
