# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171117_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleta',
            old_name='io10_valor',
            new_name='io10',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io11_valor',
            new_name='io11',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io12_valor',
            new_name='io12',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io6_valor',
            new_name='io6',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io7_valor',
            new_name='io7',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io8_valor',
            new_name='io8',
        ),
        migrations.RenameField(
            model_name='coleta',
            old_name='io9_valor',
            new_name='io9',
        ),
    ]
