# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_coleta_nivel_sinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chave_senha_requisitada',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha_foi_requisitada',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha_requisitada_em',
        ),
    ]
