# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171128_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdutor',
            name='chave_api',
            field=models.CharField(default='', max_length=25),
        ),
    ]
