# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170821_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
    ]
