# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170821_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadografico',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='constantes',
            table=None,
        ),
    ]
