# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171116_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='data1',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data3',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data4',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data5',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data6',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data7',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='data8',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida1',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida2',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida3',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida4',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida5',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida6',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida7',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='saida8',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor1',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor2',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor3',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor4',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor5',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor6',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor7',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='valor8',
        ),
        migrations.AddField(
            model_name='coleta',
            name='io10_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io10_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io11_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io11_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io12_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io12_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io6_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io6_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io7_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io7_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io8_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io8_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io9_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='io9_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transdutor',
            name='chave_api',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
