# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171117_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='data_leitura',
            field=models.DateTimeField(null=True),
        ),
    ]
