# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_coleta_data_leitura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='io10_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io11_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io12_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io6_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io7_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io8_data',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='io9_data',
        ),
    ]
