# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171117_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='data_instalacao',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='hora_instalacao',
        ),
    ]
