# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171117_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleta',
            name='nivel_sinal',
        ),
    ]
