# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171120_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdutor',
            name='hora_ponto_fim',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transdutor',
            name='hora_ponto_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transdutor',
            name='parametro_a',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transdutor',
            name='parametro_b',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
