# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20171128_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdutor',
            name='nome_io10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transdutor',
            name='nome_io11',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transdutor',
            name='nome_io7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transdutor',
            name='nome_io8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transdutor',
            name='nome_io9',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
