# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20171129_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='io10',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='io11',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='io12',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='io7',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='io8',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='io9',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
