# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_coleta_calculo_io6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdutor',
            name='parametro_a',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transdutor',
            name='parametro_b',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
