# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20171202_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='calculo_io7',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='calculo_io8',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
